---
title: "Agricultural Statistics"
author: "Hadrien"
date: "3/27/2019"
output: html_document
---

Data source: [Food and Agricultural Organization of the United Nations](http://www.fao.org/faostat/en/#data/QC)

```{r}
######################
# load and tidy data #
######################

library(tidyverse)
library(readr)

# load data
df <- read_csv("data/Production_Crops_E_All_Data_NOFLAG.csv")

# transform from wide to long format
df <- df %>% gather(Year, Value, Y1961:Y2017)

# clean up year
df$Year <-  df2$Year %>% str_remove("Y") %>% as.integer()

glimpse(df)



```

# Top production by crop (worldwide)

```{r}

# remove aggregates and yield

df <- df %>% 
  filter(Element == "Production", !grepl("Total|Primary|Rice Milled Eqv", Item))

df_total_production <-  df %>%
  group_by(Item) %>%
  summarise(tonnes_produced = sum(na.omit(Value)))

df_total_production %>% 
  top_n(20,tonnes_produced) %>%
    ggplot(aes(reorder(Item,  -tonnes_produced), tonnes_produced)) + geom_bar(stat =
                                                                        "identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))


```
 
 # Production trend 
 
```{r}
crop <- "Wheat"
country <- "Saudi Arabia"

# plot production by crop and country
df %>%
  filter( Item == crop, Area == country) %>%
  ggplot(aes(Year,Value)) + geom_point()
```
 
 